import type { PaymentDirection, PaymentDto, PaymentStatus } from "@quanti/shared";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { ApiError } from "../../api/errors";
import { PaymentDrawer } from "./PaymentDrawer";
import { createPayment, deletePayment, getPaymentDebts, getPaymentLookups, getPayments, postPayment, repostPayment, unpostPayment, updatePayment } from "./payments-api";
import { allocatedTotal, paymentToForm, toPaymentPayload, type PaymentFormValues } from "./payment-model";

type Action = "post" | "unpost" | "repost" | "delete";
export function PaymentsPage() {
  const client = useQueryClient();
  const [search, setSearch] = useState(""); const [direction, setDirection] = useState<"" | PaymentDirection>(""); const [status, setStatus] = useState<"" | PaymentStatus>("");
  const [selected, setSelected] = useState<PaymentDto | null>(null); const [drawer, setDrawer] = useState(false); const [pending, setPending] = useState<{ action: Action; payment: PaymentDto } | null>(null);
  const payments = useQuery({ queryKey: ["payments"], queryFn: getPayments }); const lookups = useQuery({ queryKey: ["payment-lookups"], queryFn: getPaymentLookups }); const debts = useQuery({ queryKey: ["payment-debts"], queryFn: getPaymentDebts });
  const refresh = async () => { await Promise.all([client.invalidateQueries({ queryKey: ["payments"] }), client.invalidateQueries({ queryKey: ["payment-debts"] })]); };
  const save = useMutation({ mutationFn: ({ values, payment }: { values: PaymentFormValues; payment: PaymentDto | null }) => payment ? updatePayment(payment.id, toPaymentPayload(values)) : createPayment(toPaymentPayload(values)), onSuccess: async () => { await refresh(); setDrawer(false); setSelected(null); } });
  const lifecycle = useMutation<void, Error, { action: Action; payment: PaymentDto }>({ mutationFn: async ({ action, payment }) => { if (action === "post") await postPayment(payment.id); else if (action === "unpost") await unpostPayment(payment.id); else if (action === "repost") await repostPayment(payment.id); else await deletePayment(payment.id); }, onSuccess: async () => { await refresh(); setPending(null); } });
  const filtered = useMemo(() => (payments.data ?? []).filter((payment) => (!direction || payment.direction === direction) && (!status || payment.status === status) && (!search.trim() || payment.number.toLowerCase().includes(search.trim().toLowerCase()))), [payments.data, direction, status, search]);
  const accountName = (id: string) => lookups.data?.accounts.find((item) => item.id === id)?.name ?? id; const counterpartyName = (id: string | null) => id ? lookups.data?.counterparties.find((item) => item.id === id)?.name ?? id : "—";
  return <section className="page payments-page" aria-labelledby="payments-title"><header className="page__header"><p className="page__eyebrow">Finance</p><h1 id="payments-title">Payments</h1></header>
    <div className="document-toolbar"><label className="search-field"><Search /><span className="visually-hidden">Search payments</span><input placeholder="Search payments" value={search} onChange={(e) => setSearch(e.target.value)} /></label><select aria-label="Direction filter" value={direction} onChange={(e) => setDirection(e.target.value as typeof direction)}><option value="">All directions</option><option value="INCOMING">Incoming</option><option value="OUTGOING">Outgoing</option></select><select aria-label="Payment status filter" value={status} onChange={(e) => setStatus(e.target.value as typeof status)}><option value="">All statuses</option><option value="DRAFT">Draft</option><option value="POSTED">Posted</option><option value="CANCELLED">Cancelled</option></select><button className="button button--primary" onClick={() => { setSelected(null); setDrawer(true); }}><Plus /> New payment</button></div>
    <div className="data-table-frame">{payments.isPending ? <div className="table-state">Loading payments…</div> : payments.isError ? <div className="table-state"><strong>Unable to load payments.</strong><span>{payments.error instanceof ApiError ? payments.error.message : "Try again."}</span></div> : filtered.length === 0 ? <div className="table-state"><strong>No payments found</strong></div> : <div className="data-table-scroll"><table className="data-table"><thead><tr><th>Number</th><th>Direction</th><th>Date</th><th>Counterparty</th><th>Account</th><th>Amount</th><th>Allocated</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((payment) => <tr key={payment.id}><td><button className="table-link" onClick={() => { setSelected(payment); setDrawer(true); }}>{payment.number}</button></td><td><span className={`direction direction--${payment.direction.toLowerCase()}`}>{payment.direction}</span></td><td>{new Date(payment.paymentDate).toLocaleDateString()}</td><td>{counterpartyName(payment.counterpartyId)}</td><td>{accountName(payment.accountId)}</td><td>{payment.amount}</td><td>{allocatedTotal(paymentToForm(payment)).toFixed(2)}</td><td><span className={`status-label status-label--${payment.status.toLowerCase()}`}>{payment.status}</span></td><td><div className="document-actions">{payment.status === "DRAFT" ? <><button onClick={() => { setSelected(payment); setDrawer(true); }}>Edit</button><button onClick={() => setPending({ action: "post", payment })}>Post</button><button onClick={() => setPending({ action: "delete", payment })}>Delete</button></> : payment.status === "POSTED" ? <><button onClick={() => { setSelected(payment); setDrawer(true); }}>View</button><button onClick={() => setPending({ action: "unpost", payment })}>Unpost</button><button onClick={() => setPending({ action: "repost", payment })}>Repost</button></> : <button onClick={() => { setSelected(payment); setDrawer(true); }}>View</button>}</div></td></tr>)}</tbody></table></div>}</div>
    {drawer ? <PaymentDrawer payment={selected} accounts={lookups.data?.accounts ?? []} counterparties={lookups.data?.counterparties ?? []} documents={lookups.data?.documents ?? []} debts={debts.data ?? []} isSaving={save.isPending} onClose={() => { setDrawer(false); setSelected(null); }} onSave={(values) => save.mutateAsync({ values, payment: selected }).then(() => undefined)} /> : null}
    {pending ? <div className="dialog-backdrop"><div className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="payment-action"><h2 id="payment-action">{pending.action[0].toUpperCase() + pending.action.slice(1)} payment?</h2><p>This will update <strong>{pending.payment.number}</strong> and its money ledger effect.</p>{lifecycle.isError ? <div className="form-alert">{lifecycle.error.message}</div> : null}<div className="confirm-dialog__actions"><button className="button button--secondary" disabled={lifecycle.isPending} onClick={() => setPending(null)}>Cancel</button><button className={pending.action === "delete" ? "button button--danger" : "button button--primary"} disabled={lifecycle.isPending} onClick={() => lifecycle.mutate(pending)}>{lifecycle.isPending ? "Updating…" : "Confirm"}</button></div></div></div> : null}
  </section>;
}
