import type { PaymentDirection, PaymentDto, PaymentStatus } from "@quanti/shared";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { useI18n } from "../../i18n";
import { PaymentDrawer } from "./PaymentDrawer";
import { createPayment, deletePayment, getPaymentDebts, getPaymentLookups, getPayments, postPayment, repostPayment, unpostPayment, updatePayment } from "./payments-api";
import { allocatedTotal, paymentToForm, toPaymentPayload, type PaymentFormValues } from "./payment-model";

type Action = "post" | "unpost" | "repost" | "delete";
export function PaymentsPage() {
  const { formatApiError, formatDate, paymentDirectionLabels, paymentStatusLabels, t } = useI18n();
  const client = useQueryClient();
  const [search, setSearch] = useState(""); const [direction, setDirection] = useState<"" | PaymentDirection>(""); const [status, setStatus] = useState<"" | PaymentStatus>("");
  const [selected, setSelected] = useState<PaymentDto | null>(null); const [drawer, setDrawer] = useState(false); const [pending, setPending] = useState<{ action: Action; payment: PaymentDto } | null>(null);
  const payments = useQuery({ queryKey: ["payments"], queryFn: getPayments }); const lookups = useQuery({ queryKey: ["payment-lookups"], queryFn: getPaymentLookups }); const debts = useQuery({ queryKey: ["payment-debts"], queryFn: getPaymentDebts });
  const refresh = async () => { await Promise.all([client.invalidateQueries({ queryKey: ["payments"] }), client.invalidateQueries({ queryKey: ["payment-debts"] })]); };
  const save = useMutation({ mutationFn: ({ values, payment }: { values: PaymentFormValues; payment: PaymentDto | null }) => payment ? updatePayment(payment.id, toPaymentPayload(values)) : createPayment(toPaymentPayload(values)), onSuccess: async (savedPayment) => {
    client.setQueryData<PaymentDto[]>(["payments"], (current = []) => current.some((item) => item.id === savedPayment.id)
      ? current.map((item) => item.id === savedPayment.id ? savedPayment : item)
      : [...current, savedPayment]);
    await client.invalidateQueries({ queryKey: ["payment-debts"] });
    setDrawer(false); setSelected(null);
  } });
  const lifecycle = useMutation<void, Error, { action: Action; payment: PaymentDto }>({ mutationFn: async ({ action, payment }) => { if (action === "post") await postPayment(payment.id); else if (action === "unpost") await unpostPayment(payment.id); else if (action === "repost") await repostPayment(payment.id); else await deletePayment(payment.id); }, onSuccess: async () => { await refresh(); setPending(null); } });
  const filtered = useMemo(() => (payments.data ?? []).filter((payment) => (!direction || payment.direction === direction) && (!status || payment.status === status) && (!search.trim() || payment.number.toLowerCase().includes(search.trim().toLowerCase()))), [payments.data, direction, status, search]);
  const accountName = (id: string) => lookups.data?.accounts.find((item) => item.id === id)?.name ?? id; const counterpartyName = (id: string | null) => id ? lookups.data?.counterparties.find((item) => item.id === id)?.name ?? id : "—";
  return <section className="page payments-page" aria-labelledby="payments-title"><header className="page__header"><p className="page__eyebrow">{t("Финансы")}</p><h1 id="payments-title">{t("Платежи")}</h1></header>
    <div className="document-toolbar"><label className="search-field"><Search /><span className="visually-hidden">{t("Поиск платежей")}</span><input placeholder={t("Поиск платежей")} value={search} onChange={(e) => setSearch(e.target.value)} /></label><select aria-label={t("Фильтр по направлению")} value={direction} onChange={(e) => setDirection(e.target.value as typeof direction)}><option value="">{t("Все направления")}</option><option value="INCOMING">{t("Входящие")}</option><option value="OUTGOING">{t("Исходящие")}</option></select><select aria-label={t("Фильтр по статусу платежа")} value={status} onChange={(e) => setStatus(e.target.value as typeof status)}><option value="">{t("Все статусы")}</option><option value="DRAFT">{t("Черновик")}</option><option value="POSTED">{t("Проведён")}</option><option value="CANCELLED">{t("Отменён")}</option></select><button className="button button--primary" onClick={() => { setSelected(null); setDrawer(true); }}><Plus /> {t("Новый платёж")}</button></div>
    <div className="data-table-frame">{payments.isPending ? <div className="table-state">{t("Загрузка платежей…")}</div> : payments.isError ? <div className="table-state"><strong>{t("Не удалось загрузить платежи.")}</strong><span>{formatApiError(payments.error)}</span></div> : filtered.length === 0 ? <div className="table-state"><strong>{t("Платежи не найдены")}</strong></div> : <div className="data-table-scroll"><table className="data-table"><thead><tr>{["Номер", "Направление", "Дата", "Контрагент", "Счёт", "Сумма", "Распределено", "Статус", "Действия"].map((label) => <th key={label}>{t(label)}</th>)}</tr></thead><tbody>{filtered.map((payment) => <tr key={payment.id}><td><button className="table-link" onClick={() => { setSelected(payment); setDrawer(true); }}>{payment.number}</button></td><td><span className={`direction direction--${payment.direction.toLowerCase()}`}>{paymentDirectionLabels[payment.direction]}</span></td><td>{formatDate(payment.paymentDate)}</td><td>{counterpartyName(payment.counterpartyId)}</td><td>{accountName(payment.accountId)}</td><td>{payment.amount}</td><td>{allocatedTotal(paymentToForm(payment)).toFixed(2)}</td><td><span className={`status-label status-label--${payment.status.toLowerCase()}`}>{paymentStatusLabels[payment.status]}</span></td><td><div className="document-actions">{payment.status === "DRAFT" ? <><button onClick={() => { setSelected(payment); setDrawer(true); }}>{t("Изменить")}</button><button onClick={() => setPending({ action: "post", payment })}>{t("Провести")}</button><button onClick={() => setPending({ action: "delete", payment })}>{t("Удалить")}</button></> : payment.status === "POSTED" ? <><button onClick={() => { setSelected(payment); setDrawer(true); }}>{t("Открыть")}</button><button onClick={() => setPending({ action: "unpost", payment })}>{t("Отменить проведение")}</button><button onClick={() => setPending({ action: "repost", payment })}>{t("Перепровести")}</button></> : <button onClick={() => { setSelected(payment); setDrawer(true); }}>{t("Открыть")}</button>}</div></td></tr>)}</tbody></table></div>}</div>
    {drawer ? <PaymentDrawer payment={selected} accounts={lookups.data?.accounts ?? []} counterparties={lookups.data?.counterparties ?? []} documents={lookups.data?.documents ?? []} payments={payments.data ?? []} debts={debts.data ?? []} isSaving={save.isPending} onClose={() => { setDrawer(false); setSelected(null); }} onSave={(values) => save.mutateAsync({ values, payment: selected }).then(() => undefined)} /> : null}
    {pending ? <div className="dialog-backdrop"><div className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="payment-action"><h2 id="payment-action">{t(pending.action === "post" ? "Провести платёж?" : pending.action === "unpost" ? "Отменить проведение платежа?" : pending.action === "repost" ? "Перепровести платёж?" : "Удалить платёж?")}</h2><p>{t("Операция изменит платёж {number} и связанные движения денежных средств.", { number: pending.payment.number })}</p>{lifecycle.isError ? <div className="form-alert">{formatApiError(lifecycle.error)}</div> : null}<div className="confirm-dialog__actions"><button className="button button--secondary" disabled={lifecycle.isPending} onClick={() => setPending(null)}>{t("Отмена")}</button><button className={pending.action === "delete" ? "button button--danger" : "button button--primary"} disabled={lifecycle.isPending} onClick={() => lifecycle.mutate(pending)}>{t(lifecycle.isPending ? "Выполнение…" : "Подтвердить")}</button></div></div></div> : null}
  </section>;
}
